#!/bin/bash
echo "=== Git Push Helper for EthervoxAI Website ==="
echo ""
echo "Your website is ready to deploy! Choose an authentication method:"
echo ""
echo "Option 1: GitHub CLI (Recommended)"
echo "  brew install gh"
echo "  gh auth login"
echo "  gh repo sync"
echo ""
echo "Option 2: Personal Access Token"
echo "  1. Visit: https://github.com/settings/tokens/new"
echo "  2. Create token with 'repo' scope"
echo "  3. Run: git push origin main"
echo "  4. Username: your-github-username"
echo "  5. Password: paste-your-token"
echo ""
echo "Option 3: SSH (if you have SSH keys)"
echo "  git remote set-url origin git@github.com:ethervox-ai/.github.git"
echo "  git push origin main"
echo ""
echo "Current status:"
git status --short --branch
echo ""
echo "Ready to push commit: $(git log -1 --oneline)"
